<properties
 pageTitle="Cancelled Python Commands"
 description="Cancelled Python Commands"
 service="Microsoft.Databricks"
 resource="Microsoft.Databricks/workspaces"
 authors="AzureData_AzureDatabricks"
 ms.author="AzureData_AzureDatabricks"
 displayOrder=""
 selfHelpType="TSG_Content"
 supportTopicIds=""
 resourceTags=""
 productPesIds=""
 cloudEnvironments="public, fairfax, usnat, ussec"
 articleId="c0a4a0d2-fddf-4fc9-b3fe-38619f11ce80"
 ownershipId="AzureData_AzureDatabricks"
/>

# Cancelled Python Commands

### Symptom

Library conflicts causing the command to get Cancelled with below message in driver logs:

`module 'x' has no attribute 'xxx'"""" or """" 'xx' object has no attribute 'xxx' `

### Troubleshooting

  - Review the driver logs to determine if there was a failure or timeout related to a library installation, also [review the libraries that are included within the runtime](https://docs.microsoft.com/en-us/azure/databricks/release-notes/runtime/releases)
  - Identify the library that is causing the issue - reproduce issue and remove libraries one after the other till issue disappears. Last removed library would likely be the problematic one.


### Solution

If something was working before, but not working now, it is usually caused by a recent upgrade of a python package and can be resolved by downgrading the problematic library version from UI or using init script.

### Next Steps

If issue persists, involve SME on Ava and file a Databricks SF ticket if needed.
